stages:
- validate_plan
- apply
- destroy

.templates:
  image:
    name: hashicorp/terraform:1.9.6
    entrypoint: [""]
  before_script:
  - terraform init

validate & plan:
  extends: .templete
  stage: validate_plan
  script:
  - terraform validate
  - terraform plan -out plan.out
cache:
  key: plan
  policy: push
  paths:
  - plan.out

apply
  extends: .templete
  stage: apply 
  script:
  - terraform apply plan.out
  cache:
    key: plan
    policy: pull
    paths: 
    - plan.out
  when: manual

destroy: 
  extends: .templete
  stage: destroy
  script:
  - terraform destroy -auto-approve
  when: manuel